<a href="https://colab.research.google.com/github/Namakando-ApertureScience/Torch-training/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
random_1 = torch.rand(7, 7)
random_1

tensor([[0.6436, 0.0822, 0.8206, 0.6916, 0.5680, 0.5682, 0.9924],
        [0.8087, 0.4822, 0.4274, 0.6966, 0.4205, 0.1864, 0.6634],
        [0.5844, 0.9525, 0.3577, 0.6582, 0.6259, 0.2692, 0.9962],
        [0.1400, 0.0829, 0.8751, 0.0608, 0.3652, 0.6663, 0.4823],
        [0.2940, 0.5181, 0.3052, 0.9748, 0.0320, 0.1798, 0.3024],
        [0.0048, 0.0481, 0.5919, 0.1677, 0.7409, 0.7865, 0.9057],
        [0.9979, 0.1714, 0.0294, 0.3570, 0.3504, 0.1027, 0.7935]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
random_2 = torch.rand(1, 7).T
print(f"Random matrix 1: {random_1} and random matrix 2: {random_2}.", end="\n\n")
print(f"Random matrix 1 type: {random_1.dtype} and random matrix 2 type: {random_2.dtype}.", end="\n\n")
print(f"Random matrix 1 shape: {random_1.shape} and random matrix 2 shape: {random_2.shape}.", end="\n\n")
print(f"Random matrix 1 size: {random_1.size()} and random matrix 2 size: {random_2.size()}.", end="\n\n")
print(f"Random matrix 1 device: {random_1.device} and random matrix 2 device: {random_2.device}.", end="\n\n")

print(random_1.type(torch.float16).dtype, end="\n\n")

# Perform matrix multiplication
product = torch.matmul(random_1, random_2)
print(f"Matrix product: {product}.", end="\n\n")
print(f"Matrix product: {product.shape}.", end="\n\n")


Random matrix 1: tensor([[0.6436, 0.0822, 0.8206, 0.6916, 0.5680, 0.5682, 0.9924],
        [0.8087, 0.4822, 0.4274, 0.6966, 0.4205, 0.1864, 0.6634],
        [0.5844, 0.9525, 0.3577, 0.6582, 0.6259, 0.2692, 0.9962],
        [0.1400, 0.0829, 0.8751, 0.0608, 0.3652, 0.6663, 0.4823],
        [0.2940, 0.5181, 0.3052, 0.9748, 0.0320, 0.1798, 0.3024],
        [0.0048, 0.0481, 0.5919, 0.1677, 0.7409, 0.7865, 0.9057],
        [0.9979, 0.1714, 0.0294, 0.3570, 0.3504, 0.1027, 0.7935]]) and random matrix 2: tensor([[0.1731],
        [0.4110],
        [0.7041],
        [0.4124],
        [0.1885],
        [0.1604],
        [0.1250]]).

Random matrix 1 type: torch.float32 and random matrix 2 type: torch.float32.

Random matrix 1 shape: torch.Size([7, 7]) and random matrix 2 shape: torch.Size([7, 1]).

Random matrix 1 size: torch.Size([7, 7]) and random matrix 2 size: torch.Size([7, 1]).

Random matrix 1 device: cpu and random matrix 2 device: cpu.

torch.float16

Matrix product: tensor([[1.3305],
   

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
random_1 = torch.rand(7, 7)
random_2 = torch.rand(1, 7).T

# Matrix multiply tensors
product = torch.matmul(random_1, random_2)
product


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(RANDOM_SEED)

# Check for access to GPU

  # One way to check
!nvidia-smi
print()

  # Second way to check
print(f"cuda is available: {torch.cuda.is_available()} \nnumber of devices: {torch.cuda.device_count()}\n")
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
A = torch.rand(size=(2, 3)).to(device)
B = torch.rand(size=(2, 3)).to(device)

print(A, A.device)
print(B, B.device)

Sat Sep 20 22:23:46 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
product = A @ B.T
print(f"{product}, {product.size()}")

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max = torch.max(product)
print(max)

# Find min
min = torch.min(product)
print(min)


tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
arg_max = product.argmax()
print(arg_max)

# Find arg min
arg_min = product.argmin()
print(arg_min)

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeezed_tensor = torch.squeeze(tensor)

# Print out tensors and their shapes
print(tensor, tensor.shape)
print(squeezed_tensor, squeezed_tensor.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
